# Generated by Django 4.1.2 on 2022-11-09 22:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('priority', models.CharField(choices=[('l', 'Low'), ('m', 'Medium'), ('h', 'High')], max_length=1)),
                ('status', models.CharField(choices=[('o', 'Open'), ('w', 'Work in Progress'), ('f', 'Fixed')], default='o', max_length=1)),
            ],
        ),
    ]
